# Generated by Django 4.2.17 on 2025-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={},
        ),
        migrations.AlterField(
            model_name='supplement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
